version: '3'
services:
  bot:
    build: .
    command: python3 bot.py
    environment:
      BOT_TOKEN : "${BOT_TOKEN}"
      LOG_LEVEL: "${LOG_LEVEL}"
    volumes:
     - .:/code
  #TODO: consider adding bot depends on redis and then --no-deps in the dev ru.sh
  redis:
    image: "redis:alpine"
